services:
  - docker

language: bash

  
branches:
  only:
  - test
 
script:
  - ./build.sh
  - ./deploy.sh -c docker -t
  - ./deploy.sh -c docker -i kruize:$(cat .kruize-version) --timeout=10
  - docker logs kruize
  - docker logs kruize | grep "CPU Limit"; echo "** $?"
  - echo "***** $?"
  - result=$?
  - echo "result = ${result}"
  - |
    if [ ${result} -ne 0 ]; then 
      echo "Kruize sanity test failed! CPU Limit not found in kruize docker logs!"
      exit 1
    fi
  - docker logs kruize | grep -i "error"
  - echo "***** $?"
  - result=$?
  - echo "result = $result"
  - |
    if [ ${result} -ne 1 ]; then
      echo "Kruize sanity test failed! Error found in kruize docker logs!"
      exit 1
    fi
  - docker logs kruize | grep -i "exception"
  - result=$?
  - echo "result = $result"
  - |
    if [ ${result} -ne 1 ]; then
      echo "Kruize sanity test failed! Exception found in kruize docker logs!"
      exit 1
    fi
  - exit 0

  
